/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameWindow;

import card_deck.*;

/**
 *
 * @author tuf62546
 */
public class BlackjackWindow extends javax.swing.JFrame {

    /**
     * Creates new form BlackjackWindow
     */
    Deck deck;
    BlackjackPlayer player, cpu;
    Blackjack game;

    public BlackjackWindow() {
        initComponents();
        createNewGame();
        game = new Blackjack();
    }

    public void createNewGame() {
        deck = new Deck();
        player = new BlackjackPlayer();
        cpu = new BlackjackPlayer();

        /* Initial game state */
        for (int i = 0; i < 2; i++) {
            cpu.draw(cpu.hand, deck);
            player.draw(player.hand, deck);
        }

        if (player.hand.cards.get(0).value.equals(player.hand.cards.get(1).value)) {
            split.setVisible(true);
        } else {
            split.setVisible(false);
        }

        newGame.setVisible(false);
        /*  Set buttons for 2nd hand to false initially */
        hit2.setVisible(false);
        stay2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hit = new javax.swing.JButton();
        split = new javax.swing.JButton();
        stay = new javax.swing.JButton();
        newGame = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        hit2 = new javax.swing.JButton();
        stay2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hit.setText("Hit   ");
        hit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitButton(evt);
            }
        });

        split.setText("Split");
        split.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                splitButton(evt);
            }
        });

        stay.setText("Stay");
        stay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stayButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hit)
                    .addComponent(stay)
                    .addComponent(split))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(split)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stay))
        );

        newGame.setText("New Game");
        newGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameButton(evt);
            }
        });

        hit2.setText("Hit   ");
        hit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hit2Button(evt);
            }
        });

        stay2.setText("Stay");
        stay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stay2Button(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stay2)
                    .addComponent(hit2))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(hit2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stay2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(newGame)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newGame)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitButton
        player.hit(player.hand, deck);
        if (player.hand.handCount >= 21) {
            hit.setVisible(false);
            stay.setVisible(false);
            game.dealerDraw(player, cpu, deck);
            if (!stay.isVisible() && !stay2.isVisible()) {
                newGame.setVisible(true);
            }
        }
        split.setVisible(false);
    }//GEN-LAST:event_hitButton

    private void splitButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_splitButton
        // TODO add your handling code here:        
        player.split();
        player.hit(player.hand, deck);
        player.hit(player.hand2, deck);
        split.setVisible(false);
        hit2.setVisible(true);
        stay2.setVisible(true);
    }//GEN-LAST:event_splitButton


    private void stayButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stayButton
        if (stay.isVisible() && !stay2.isVisible()) {
            /* Dealer draws until it beats one hand or busts */
            game.dealerDraw(player, cpu, deck);
        }
        hit.setVisible(false);
        stay.setVisible(false);
        if (!stay.isVisible() && !stay2.isVisible()) {
            newGame.setVisible(true);
        }
    }//GEN-LAST:event_stayButton

    private void newGameButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButton
        // TODO add your handling code here:
        createNewGame();
        newGame.setVisible(false);
        hit.setVisible(true);
        stay.setVisible(true);
    }//GEN-LAST:event_newGameButton

    private void hit2Button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hit2Button
        player.hit(player.hand2, deck);
        if (player.hand2.handCount >= 21) {
            hit2.setVisible(false);
            stay2.setVisible(false);
            game.playerWin(player.hand2, cpu.hand);
            if (!stay.isVisible() && !stay2.isVisible()) {
                newGame.setVisible(true);
            }
        }
    }//GEN-LAST:event_hit2Button

    private void stay2Button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stay2Button
        if (!stay.isVisible() && stay2.isVisible()) {
            game.dealerDraw2(player, cpu, deck);
        }
        hit2.setVisible(false);
        stay2.setVisible(false);
        game.playerWin(player.hand2, cpu.hand);
        if (!stay.isVisible() && !stay2.isVisible()) {
            newGame.setVisible(true);
        }
    }//GEN-LAST:event_stay2Button

    /* Use these function for tests */
    public void newGameButton() {
        this.newGameButton(null);
    }

    public void hitButton() {
        this.hitButton(null);
    }

    public void hit2Button() {
        this.hit2Button(null);
    }

    public void splitButton() {
        this.splitButton(null);
    }

    public void stayButton() {
        this.stayButton(null);
    }

    public void stay2Button() {
        this.stay2Button(null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hit;
    private javax.swing.JButton hit2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton newGame;
    private javax.swing.JButton split;
    private javax.swing.JButton stay;
    private javax.swing.JButton stay2;
    // End of variables declaration//GEN-END:variables
}
