/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gameWindow;

import card_deck.*;
import javax.swing.JButton;
import visualManager.*;

/**
 *
 * @author tuf62546
 */
public class BlackjackWindow extends javax.swing.JFrame {

    /**
     * Creates new form BlackjackWindow
     */
    Deck deck;
    BlackjackPlayer player, cpu;
    Blackjack game;
    visualManager v;

    private int wins, losses, ties;

    public BlackjackWindow() {
        initComponents();
        v = new visualManager();
        game = new Blackjack();
        wins = losses = ties = 0;
        createNewGame();
    }

    public void createNewGame() {
        deck = new Deck();
        player = new BlackjackPlayer();
        cpu = new BlackjackPlayer();
        player.hand2 = new Hand();

        /* Initial game state */
        for (int i = 0; i < 2; i++) {
            cpu.draw(cpu.hand, deck);
            player.draw(player.hand, deck);
        }

        if (player.getCardValue(player.hand, 0) == player.getCardValue(player.hand, 1)) {
            split.setVisible(true);
        } else {
            split.setVisible(false);
        }

        newGame.setVisible(false);
        /*  Set buttons for 2nd hand to false initially */
        hit2.setVisible(false);
        stay2.setVisible(false);

        hideLabels();
        firstHand[0].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(player.hand, 0))));
        firstHand[1].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(player.hand, 1))));
        dealerHand[0].setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + 0 + ".png")));
        dealerHand[1].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(cpu.hand, 1))));

        record.setText("Wins: " + game.wins + " Losses: " + game.losses + " Ties: " + game.ties);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hit = new javax.swing.JButton();
        split = new javax.swing.JButton();
        stay = new javax.swing.JButton();
        newGame = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        hit2 = new javax.swing.JButton();
        stay2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        for (int i = 0; i < 8; i++) {
            firstHand[i] = new javax.swing.JLabel();
        }
        for (int i = 0; i < 8; i++) {
            secondHand[i] = new javax.swing.JLabel();
        }
        for (int i = 0; i < 8; i++) {
            dealerHand[i] = new javax.swing.JLabel();
        }
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        record = new javax.swing.JLabel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        hit.setText(
                "Hit   ");
        hit.addMouseListener(new java.awt.event.MouseAdapter() {

            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitButton(evt);
            }
        }
        );

        split.setText("Split");
        split.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                splitButton(evt);
            }
        });

        stay.setText("Stay");
        stay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stayButton(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hit)
                                        .addComponent(stay)
                                        .addComponent(split))
                                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(split)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stay))
        );

        newGame.setText("New Game");
        newGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameButton(evt);
            }
        });

        hit2.setText("Hit   ");
        hit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hit2Button(evt);
            }
        });

        stay2.setText("Stay");
        stay2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stay2Button(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stay2)
                                        .addComponent(hit2))
                                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(hit2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stay2))
        );

        firstHand[0].setText("jLabel1");

        firstHand[1].setText("jLabel2");

        firstHand[2].setText("jLabel3");

        firstHand[3].setText("jLabel4");

        firstHand[4].setText("jLabel5");

        firstHand[5].setText("jLabel6");

        firstHand[6].setText("jLabel7");

        firstHand[7].setText("jLabel8");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(firstHand[0])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstHand[1])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstHand[2])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstHand[3])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstHand[4])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstHand[5])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstHand[6])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstHand[7])
                                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap(56, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstHand[0])
                                        .addComponent(firstHand[1])
                                        .addComponent(firstHand[2])
                                        .addComponent(firstHand[3])
                                        .addComponent(firstHand[4])
                                        .addComponent(firstHand[5])
                                        .addComponent(firstHand[6])
                                        .addComponent(firstHand[7]))
                                .addGap(50, 50, 50))
        );

        secondHand[0].setText("jLabel9");

        secondHand[1].setText("jLabel10");

        secondHand[2].setText("jLabel11");

        secondHand[3].setText("jLabel12");

        secondHand[4].setText("jLabel13");

        secondHand[5].setText("jLabel14");

        secondHand[6].setText("jLabel15");

        secondHand[7].setText("jLabel16");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(secondHand[0])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondHand[1])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondHand[2])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondHand[3])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondHand[4])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondHand[5])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondHand[6])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondHand[7])
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap(62, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(secondHand[0])
                                        .addComponent(secondHand[1])
                                        .addComponent(secondHand[2])
                                        .addComponent(secondHand[3])
                                        .addComponent(secondHand[4])
                                        .addComponent(secondHand[5])
                                        .addComponent(secondHand[6])
                                        .addComponent(secondHand[7]))
                                .addGap(50, 50, 50))
        );

        dealerHand[0].setText("jLabel17");

        dealerHand[1].setText("jLabel18");

        dealerHand[2].setText("jLabel19");

        dealerHand[3].setText("jLabel20");

        dealerHand[4].setText("jLabel21");

        dealerHand[5].setText("jLabel22");

        dealerHand[6].setText("jLabel23");

        dealerHand[7].setText("jLabel24");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dealerHand[0])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerHand[1])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerHand[2])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerHand[3])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerHand[4])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerHand[5])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerHand[6])
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dealerHand[7])
                                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(dealerHand[0])
                                        .addComponent(dealerHand[1])
                                        .addComponent(dealerHand[2])
                                        .addComponent(dealerHand[3])
                                        .addComponent(dealerHand[4])
                                        .addComponent(dealerHand[5])
                                        .addComponent(dealerHand[6])
                                        .addComponent(dealerHand[7]))
                                .addGap(42, 42, 42))
        );

        record.setText("Wins: 0 Losses: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(98, 98, 98)
                                                .addComponent(newGame)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(record)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(record)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(newGame)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }

    private void hitButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitButton
        player.hit(player.hand, deck);
        int i = player.hand.cards.size() - 1;
        firstHand[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(player.hand, i))));
        firstHand[i].setVisible(true);
        if (player.hand.count >= 21) {
            hit.setVisible(false);
            stay.setVisible(false);

            if (!stay.isVisible() && !stay2.isVisible()) {
                updateRecord();
                newGame.setVisible(true);
            }
        }
        split.setVisible(false);
    }//GEN-LAST:event_hitButton

    private void splitButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_splitButton
        // TODO add your handling code here:        
        player.split();
        player.hit(player.hand, deck);
        player.hit(player.hand2, deck);
        firstHand[1].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(player.hand, 1))));
        secondHand[0].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(player.hand2, 0))));
        secondHand[1].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(player.hand2, 1))));
        secondHand[0].setVisible(true);
        secondHand[1].setVisible(true);

        split.setVisible(false);
        hit2.setVisible(true);
        stay2.setVisible(true);
    }//GEN-LAST:event_splitButton


    private void stayButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stayButton
        hit.setVisible(false);
        split.setVisible(false);
        stay.setVisible(false);
        if (!stay.isVisible() && !stay2.isVisible()) {
            updateRecord();
            newGame.setVisible(true);
        }
    }//GEN-LAST:event_stayButton

    private void newGameButton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameButton
        // TODO add your handling code here:
        createNewGame();
        newGame.setVisible(false);
        hit.setVisible(true);
        stay.setVisible(true);
    }//GEN-LAST:event_newGameButton

    private void hit2Button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hit2Button
        player.hit(player.hand2, deck);
        int i = player.hand2.cards.size() - 1;
        secondHand[i].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(player.hand2, i))));
        secondHand[i].setVisible(true);
        if (player.hand2.count >= 21) {
            hit2.setVisible(false);
            stay2.setVisible(false);

            if (!stay.isVisible() && !stay2.isVisible()) {
                updateRecord();
                newGame.setVisible(true);
            }
        }
    }//GEN-LAST:event_hit2Button

    private void stay2Button(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stay2Button
        hit2.setVisible(false);
        stay2.setVisible(false);
        if (!stay.isVisible() && !stay2.isVisible()) {
            updateRecord();
            newGame.setVisible(true);
        }
    }//GEN-LAST:event_stay2Button

    /* Get the image file name of a card in the player's hand */
    private String getCard(Hand h, int index) {
        return v.getCardLocation(h.cards.get(index));
    }

    private void hideLabels() {
        for (int i = 0; i < 8; i++) {
            firstHand[i].setText("");
            secondHand[i].setText("");
            dealerHand[i].setText("");
            secondHand[i].setVisible(false);
        }

        for (int i = 2; i < 8; i++) {
            firstHand[i].setVisible(false);
            dealerHand[i].setVisible(false);
        }
    }

    private void updateRecord() {
        this.wins = game.wins;
        this.ties = game.ties;
        this.losses = game.losses;
        game.decideWinner(player, cpu, deck);
        if (player.hand2.cards.isEmpty()) {
            if (game.wins > this.wins) {
                record.setText("You win!");
                wins++;
            } else if (game.ties > this.ties) {
                record.setText("You tied.");
            } else {
                record.setText("You lost...");
            }
        } else {
            if (game.wins - this.wins == 2) {
                record.setText("You won both hands!");
                wins += 2;
            } else if (game.ties - this.ties == 2) {
                record.setText("You tied both hands.");
                ties += 2;
            } else if (game.losses - this.losses == 2) {
                record.setText("You lost both hands...");
                losses += 2;
            } else if (game.wins - this.wins == 1 && game.losses - this.losses == 1) {
                record.setText("You won one hand and lost the other.");
                wins++;
                losses++;
            } else if (game.wins - this.wins == 1 && game.ties - this.ties == 1) {
                record.setText("You won one hand and tied the other.");
                wins++;
                ties++;               
            } else if (game.ties - this.ties == 1 && game.losses - this.losses == 1) {
                record.setText("You tied one hand and lost the other.");
                ties++;
                losses++; 
            }
        }
        for (int j = 0; j < cpu.hand.cards.size(); j++) {
            dealerHand[j].setIcon(new javax.swing.ImageIcon(getClass().getResource(getCard(cpu.hand, j))));
            dealerHand[j].setVisible(true);
        }
    }

    /* Use these function for testing purposes */
    public void newGameButton() {
        this.newGameButton(null);
    }

    public void hitButton() {
        this.hitButton(null);
    }

    public void hit2Button() {
        this.hit2Button(null);
    }

    public void splitButton() {
        this.splitButton(null);
    }

    public void stayButton() {
        this.stayButton(null);
    }

    public void stay2Button() {
        this.stay2Button(null);
    }
    
    public javax.swing.JButton getSplit(){
        return split; 
    }
    
    public javax.swing.JLabel getRecord(){
        return record; 
    }
    
    /*  end of functions used for testing */

    private javax.swing.JButton hit;
    private javax.swing.JButton hit2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton newGame;
    private javax.swing.JButton split;
    private javax.swing.JButton stay;
    private javax.swing.JButton stay2;
    private javax.swing.JLabel record;
    javax.swing.JLabel[] firstHand = new javax.swing.JLabel[8];
    javax.swing.JLabel[] secondHand = new javax.swing.JLabel[8];
    javax.swing.JLabel[] dealerHand = new javax.swing.JLabel[8];
}
